const LOCATION_CATALOG = {
  provinces: [
    { id: "1", name: "Koshi" },
    { id: "2", name: "Madhesh" },
    { id: "3", name: "Bagmati" },
    { id: "4", name: "Gandaki" },
    { id: "5", name: "Lumbini" },
    { id: "6", name: "Karnali" },
    { id: "7", name: "Sudurpashchim" },
  ],
  zones: [
    { id: "mechi", name: "Mechi" },
    { id: "koshi", name: "Koshi" },
    { id: "sagarmatha", name: "Sagarmatha" },
    { id: "janakpur", name: "Janakpur" },
    { id: "bagmati", name: "Bagmati" },
    { id: "narayani", name: "Narayani" },
    { id: "gandaki", name: "Gandaki" },
    { id: "dhaulagiri", name: "Dhaulagiri" },
    { id: "lumbini", name: "Lumbini" },
    { id: "rapti", name: "Rapti" },
    { id: "bheri", name: "Bheri" },
    { id: "karnali", name: "Karnali" },
    { id: "seti", name: "Seti" },
    { id: "mahakali", name: "Mahakali" },
  ],
  districts: [
    { name: "Bhojpur", province_id: "1", zone_id: "koshi" },
    { name: "Dhankuta", province_id: "1", zone_id: "koshi" },
    { name: "Ilam", province_id: "1", zone_id: "mechi" },
    { name: "Jhapa", province_id: "1", zone_id: "mechi" },
    { name: "Khotang", province_id: "1", zone_id: "sagarmatha" },
    { name: "Morang", province_id: "1", zone_id: "koshi" },
    { name: "Okhaldhunga", province_id: "1", zone_id: "sagarmatha" },
    { name: "Panchthar", province_id: "1", zone_id: "mechi" },
    { name: "Sankhuwasabha", province_id: "1", zone_id: "koshi" },
    { name: "Solukhumbu", province_id: "1", zone_id: "sagarmatha" },
    { name: "Sunsari", province_id: "1", zone_id: "koshi" },
    { name: "Taplejung", province_id: "1", zone_id: "mechi" },
    { name: "Terhathum", province_id: "1", zone_id: "koshi" },
    { name: "Udayapur", province_id: "1", zone_id: "sagarmatha" },

    { name: "Bara", province_id: "2", zone_id: "narayani" },
    { name: "Dhanusha", province_id: "2", zone_id: "janakpur" },
    { name: "Mahottari", province_id: "2", zone_id: "janakpur" },
    { name: "Parsa", province_id: "2", zone_id: "narayani" },
    { name: "Rautahat", province_id: "2", zone_id: "narayani" },
    { name: "Saptari", province_id: "2", zone_id: "sagarmatha" },
    { name: "Sarlahi", province_id: "2", zone_id: "janakpur" },
    { name: "Siraha", province_id: "2", zone_id: "sagarmatha" },

    { name: "Bhaktapur", province_id: "3", zone_id: "bagmati" },
    { name: "Chitwan", province_id: "3", zone_id: "narayani" },
    { name: "Dhading", province_id: "3", zone_id: "bagmati" },
    { name: "Dolakha", province_id: "3", zone_id: "janakpur" },
    { name: "Kathmandu", province_id: "3", zone_id: "bagmati" },
    { name: "Kavrepalanchok", province_id: "3", zone_id: "bagmati" },
    { name: "Lalitpur", province_id: "3", zone_id: "bagmati" },
    { name: "Makwanpur", province_id: "3", zone_id: "narayani" },
    { name: "Nuwakot", province_id: "3", zone_id: "bagmati" },
    { name: "Ramechhap", province_id: "3", zone_id: "janakpur" },
    { name: "Rasuwa", province_id: "3", zone_id: "bagmati" },
    { name: "Sindhuli", province_id: "3", zone_id: "janakpur" },
    { name: "Sindhupalchok", province_id: "3", zone_id: "bagmati" },

    { name: "Baglung", province_id: "4", zone_id: "dhaulagiri" },
    { name: "Gorkha", province_id: "4", zone_id: "gandaki" },
    { name: "Kaski", province_id: "4", zone_id: "gandaki" },
    { name: "Lamjung", province_id: "4", zone_id: "gandaki" },
    { name: "Manang", province_id: "4", zone_id: "gandaki" },
    { name: "Mustang", province_id: "4", zone_id: "dhaulagiri" },
    { name: "Myagdi", province_id: "4", zone_id: "dhaulagiri" },
    { name: "Nawalpur", province_id: "4", zone_id: "lumbini" },
    { name: "Parbat", province_id: "4", zone_id: "dhaulagiri" },
    { name: "Syangja", province_id: "4", zone_id: "gandaki" },
    { name: "Tanahun", province_id: "4", zone_id: "gandaki" },

    { name: "Arghakhanchi", province_id: "5", zone_id: "lumbini" },
    { name: "Banke", province_id: "5", zone_id: "bheri" },
    { name: "Bardiya", province_id: "5", zone_id: "bheri" },
    { name: "Dang", province_id: "5", zone_id: "rapti" },
    { name: "Gulmi", province_id: "5", zone_id: "lumbini" },
    { name: "Kapilvastu", province_id: "5", zone_id: "lumbini" },
    { name: "Palpa", province_id: "5", zone_id: "lumbini" },
    { name: "Parasi", province_id: "5", zone_id: "lumbini" },
    { name: "Pyuthan", province_id: "5", zone_id: "rapti" },
    { name: "Rolpa", province_id: "5", zone_id: "rapti" },
    { name: "Rukum East", province_id: "5", zone_id: "rapti" },
    { name: "Rupandehi", province_id: "5", zone_id: "lumbini" },

    { name: "Dailekh", province_id: "6", zone_id: "bheri" },
    { name: "Dolpa", province_id: "6", zone_id: "karnali" },
    { name: "Humla", province_id: "6", zone_id: "karnali" },
    { name: "Jajarkot", province_id: "6", zone_id: "bheri" },
    { name: "Jumla", province_id: "6", zone_id: "karnali" },
    { name: "Kalikot", province_id: "6", zone_id: "karnali" },
    { name: "Mugu", province_id: "6", zone_id: "karnali" },
    { name: "Rukum West", province_id: "6", zone_id: "rapti" },
    { name: "Salyan", province_id: "6", zone_id: "rapti" },
    { name: "Surkhet", province_id: "6", zone_id: "bheri" },

    { name: "Achham", province_id: "7", zone_id: "seti" },
    { name: "Baitadi", province_id: "7", zone_id: "mahakali" },
    { name: "Bajhang", province_id: "7", zone_id: "seti" },
    { name: "Bajura", province_id: "7", zone_id: "seti" },
    { name: "Dadeldhura", province_id: "7", zone_id: "mahakali" },
    { name: "Darchula", province_id: "7", zone_id: "mahakali" },
    { name: "Doti", province_id: "7", zone_id: "seti" },
    { name: "Kailali", province_id: "7", zone_id: "seti" },
    { name: "Kanchanpur", province_id: "7", zone_id: "mahakali" },
  ],
};

if (typeof globalThis !== "undefined") {
  globalThis.ADMIN_LOCATION_CATALOG = LOCATION_CATALOG;
}

if (typeof module !== "undefined") {
  module.exports = LOCATION_CATALOG;
}
