const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
const {
  escapeXml,
  escapeYaml,
  runCommand,
  stringOrDefault,
  trimLog,
} = require("./generator-utils");

let cachedFlutterCommand = null;

function buildFlutterOutput(paths, business, appData) {
  fs.mkdirSync(paths.outputDir, { recursive: true });
  fs.mkdirSync(paths.apkDir, { recursive: true });

  ensureFlutterProject(paths, business, appData);
  fs.writeFileSync(paths.flutterMainPath, buildFlutterMainSource(business, appData), "utf8");
  fs.writeFileSync(paths.flutterManifestPath, buildAndroidManifest(appData), "utf8");
  updateFlutterPubspec(paths.flutterPubspecPath, appData);

  const build = runCommand(
    getFlutterCommand(),
    ["build", "apk", "--release"],
    paths.flutterProjectDir,
    20 * 60 * 1000
  );
  fs.writeFileSync(paths.apkLogPath, build.log, "utf8");

  if (build.status !== 0) {
    return {
      success: false,
      exit_code: build.status,
      apk_path: paths.apkPath,
      log_path: paths.apkLogPath,
      message: "Flutter build failed. Review the build log for details.",
      log_excerpt: trimLog(build.log),
    };
  }

  const generatedApkPath = path.join(
    paths.flutterProjectDir,
    "build",
    "app",
    "outputs",
    "flutter-apk",
    "app-release.apk"
  );

  if (!fs.existsSync(generatedApkPath)) {
    return {
      success: false,
      exit_code: build.status,
      apk_path: paths.apkPath,
      log_path: paths.apkLogPath,
      message: "Flutter reported success, but the APK file was not found.",
      log_excerpt: trimLog(build.log),
    };
  }

  fs.copyFileSync(generatedApkPath, paths.apkPath);
  return {
    success: true,
    exit_code: build.status,
    apk_path: paths.apkPath,
    log_path: paths.apkLogPath,
    message: "Flutter app built successfully.",
    log_excerpt: trimLog(build.log),
  };
}

function ensureFlutterProject(paths, business, appData) {
  const hasProject =
    fs.existsSync(paths.flutterPubspecPath) &&
    fs.existsSync(path.join(paths.flutterProjectDir, "android")) &&
    fs.existsSync(path.join(paths.flutterProjectDir, "lib"));

  if (hasProject) {
    return;
  }

  const projectName = buildFlutterProjectName(business);
  fs.mkdirSync(paths.outputDir, { recursive: true });

  const result = runCommand(
    getFlutterCommand(),
    [
      "create",
      "--platforms=android",
      "--project-name",
      projectName,
      "--org",
      "com.schooldnd.generated",
      "flutter_app",
    ],
    paths.outputDir,
    10 * 60 * 1000
  );

  if (result.status !== 0) {
    throw new Error(`Unable to create Flutter project.\n${trimLog(result.log)}`);
  }

  fs.writeFileSync(
    path.join(paths.flutterProjectDir, "README.md"),
    `# ${appData.app_name}\n\nGenerated by Generator Studio for ${business.name}.\n`,
    "utf8"
  );
}

function getFlutterCommand() {
  if (cachedFlutterCommand) {
    return cachedFlutterCommand;
  }

  const isWindows = process.platform === "win32";
  const directCandidates = [
    process.env.FLUTTER_BIN,
    process.env.FLUTTER_HOME
      ? path.join(process.env.FLUTTER_HOME, "bin", isWindows ? "flutter.bat" : "flutter")
      : "",
  ].filter(Boolean);

  for (const candidate of directCandidates) {
    if (fs.existsSync(candidate)) {
      cachedFlutterCommand = candidate;
      return cachedFlutterCommand;
    }
  }

  if (isWindows) {
    const probe = spawnSync("where.exe", ["flutter"], {
      encoding: "utf8",
      windowsHide: true,
    });
    const candidates = String(probe.stdout || "")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    const preferred =
      candidates.find((line) => line.toLowerCase().endsWith(".bat")) || candidates[0];
    if (preferred) {
      cachedFlutterCommand = preferred;
      return cachedFlutterCommand;
    }
  }

  cachedFlutterCommand = "flutter";
  return cachedFlutterCommand;
}

function buildFlutterProjectName(business) {
  const base = `${business.slug}_${String(business.id || "")
    .replace(/[^a-z0-9]+/gi, "_")
    .toLowerCase()}`;
  const normalized = base
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^([^a-z]+)/, "app_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized.slice(0, 36) || "institute_app";
}

function buildAndroidManifest(appData) {
  return `<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:label="${escapeXml(appData.app_name)}"
        android:name="\${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`;
}

function updateFlutterPubspec(pubspecPath, appData) {
  if (!fs.existsSync(pubspecPath)) {
    return;
  }

  const current = fs.readFileSync(pubspecPath, "utf8");
  const projectName = readYamlValue(current, "name") || "flutter_app";
  const sdkConstraint = readYamlValue(current, "sdk", true) || "^3.7.0";

  const next = `name: ${projectName}
description: "${escapeYaml(appData.app_name)}"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ${sdkConstraint}

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`;

  fs.writeFileSync(pubspecPath, next, "utf8");
}

function readYamlValue(content, key, nested = false) {
  const pattern = nested
    ? new RegExp(`^\\s*${key}:\\s*(.+)$`, "m")
    : new RegExp(`^${key}:\\s*(.+)$`, "m");
  const match = String(content || "").match(pattern);
  return match ? String(match[1] || "").trim() : "";
}

function buildFlutterMainSource(business, appData) {
  const payload = JSON.stringify(
    {
      business: {
        id: business.id,
        slug: business.slug,
        name: business.name,
        type: business.type,
        locationLabel: business.location_label,
        affiliation: business.affiliation,
      },
      app: appData,
    },
    null,
    2
  );

  const sections = [];

  sections.push(`import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_player/video_player.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart';

const String kInstitutePayload = ${JSON.stringify(payload)};

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  final Map<String, dynamic> payload = jsonDecode(kInstitutePayload) as Map<String, dynamic>;
  runApp(GeneratedInstituteApp(payload: payload));
}

class GeneratedInstituteApp extends StatelessWidget {
  const GeneratedInstituteApp({super.key, required this.payload});

  final Map<String, dynamic> payload;

  @override
  Widget build(BuildContext context) {
    final app = _mapValue(payload['app']);
    final seed = _parseColor(_text(app['theme_seed'], '#355DA8'));
    final base = ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(seedColor: seed, brightness: Brightness.light),
    );

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: _text(app['app_name'], 'Institute App'),
      theme: base.copyWith(
        scaffoldBackgroundColor: const Color(0xFFF5F0E8),
        textTheme: GoogleFonts.manropeTextTheme(base.textTheme).copyWith(
          headlineLarge: GoogleFonts.sora(textStyle: base.textTheme.headlineLarge, fontWeight: FontWeight.w700),
          headlineMedium: GoogleFonts.sora(textStyle: base.textTheme.headlineMedium, fontWeight: FontWeight.w700),
          headlineSmall: GoogleFonts.sora(textStyle: base.textTheme.headlineSmall, fontWeight: FontWeight.w700),
          titleLarge: GoogleFonts.sora(textStyle: base.textTheme.titleLarge, fontWeight: FontWeight.w700),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          surfaceTintColor: Colors.transparent,
          elevation: 0,
        ),
      ),
      home: InstituteShell(payload: payload),
    );
  }
}

class _PageItem {
  const _PageItem({required this.label, required this.icon});
  final String label;
  final IconData icon;
}

class InstituteShell extends StatefulWidget {
  const InstituteShell({super.key, required this.payload});

  final Map<String, dynamic> payload;

  @override
  State<InstituteShell> createState() => _InstituteShellState();
}

class _InstituteShellState extends State<InstituteShell> {
  static const List<_PageItem> _pages = <_PageItem>[
    _PageItem(label: 'Home', icon: Icons.home_rounded),
    _PageItem(label: 'Academics', icon: Icons.school_rounded),
    _PageItem(label: 'People', icon: Icons.groups_rounded),
    _PageItem(label: 'Media', icon: Icons.play_circle_outline_rounded),
    _PageItem(label: 'Updates', icon: Icons.campaign_rounded),
  ];

  int _currentIndex = 0;

  Map<String, dynamic> get _business => _mapValue(widget.payload['business']);
  Map<String, dynamic> get _app => _mapValue(widget.payload['app']);

  @override
  Widget build(BuildContext context) {
    final app = _app;
    final contact = _mapValue(app['contact']);
    final websiteUrl = _text(contact['website']);
    final screens = <Widget>[
      HomeScreen(business: _business, app: app, onNavigate: _navigateTo),
      AcademicsScreen(business: _business, app: app),
      PeopleScreen(business: _business, app: app),
      MediaScreen(business: _business, app: app),
      UpdatesScreen(business: _business, app: app),
    ];

    return Scaffold(
      extendBody: true,
      floatingActionButton: websiteUrl.isNotEmpty
          ? FloatingActionButton.small(
              tooltip: 'Open website',
              onPressed: () => _openExternal(websiteUrl),
              child: const Icon(Icons.open_in_new_rounded),
            )
          : null,
      body: SafeArea(
        bottom: false,
        child: DecoratedBox(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                Colors.white.withOpacity(0.9),
                Theme.of(context).colorScheme.primary.withOpacity(0.06),
                const Color(0xFFF5F0E8),
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
          child: IndexedStack(
            index: _currentIndex,
            children: screens,
          ),
        ),
      ),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _currentIndex,
        onDestinationSelected: _navigateTo,
        destinations: _pages
            .map(
              (page) => NavigationDestination(
                icon: Icon(page.icon),
                label: page.label,
              ),
            )
            .toList(),
      ),
    );
  }

  void _navigateTo(int index) {
    setState(() {
      _currentIndex = index;
    });
  }
}

class _AppHeaderTitle extends StatelessWidget {
  const _AppHeaderTitle({
    required this.name,
    required this.subtitle,
    required this.logoUrl,
  });

  final String name;
  final String subtitle;
  final String logoUrl;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        _LogoAvatar(name: name, logoUrl: logoUrl, radius: 22),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                name,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800),
              ),
              Text(
                subtitle,
                style: Theme.of(context).textTheme.labelMedium?.copyWith(
                      color: Theme.of(context).colorScheme.primary,
                    ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({
    super.key,
    required this.business,
    required this.app,
    required this.onNavigate,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;
  final ValueChanged<int> onNavigate;

  @override
  Widget build(BuildContext context) {
    final quickFacts = _blockList(app['quick_facts']);
    final highlights = _blockList(app['highlights']);
    final notices = _stringList(app['notices']);

    return ListView(
      padding: const EdgeInsets.fromLTRB(18, 8, 18, 120),
      children: [
        _HomeHero(
          business: business,
          app: app,
          onNavigate: onNavigate,
        ),
        const SizedBox(height: 18),
        if (quickFacts.isNotEmpty) ...[
          const _SectionTitle(title: 'Quick Facts', subtitle: 'At a glance'),
          const SizedBox(height: 12),
          Wrap(
            spacing: 12,
            runSpacing: 12,
            children: quickFacts
                .map((item) => _MetricTile(value: _text(item['value']), label: _text(item['label'])))
                .toList(),
          ),
          const SizedBox(height: 22),
        ],
        const _SectionTitle(title: 'Introduction', subtitle: 'Institute overview'),
        _GlassCard(
          child: Text(
            _text(app['intro_body']),
            style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.65),
          ),
        ),
        if (highlights.isNotEmpty) ...[
          const SizedBox(height: 22),
          const _SectionTitle(title: 'Highlights', subtitle: 'What stands out'),
          const SizedBox(height: 12),
          ...highlights.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _DetailCard(
                title: _text(item['title']),
                body: _text(item['body']),
              ),
            ),
          ),
        ],
        if (_text(app['director_message']).isNotEmpty) ...[
          const SizedBox(height: 22),
          _DetailCard(
            title: _text(app['director_name'], 'Leadership message'),
            subtitle: _text(app['director_role']),
            body: _text(app['director_message']),
          ),
        ],
        if (notices.isNotEmpty) ...[
          const SizedBox(height: 22),
          const _SectionTitle(title: 'Current Notices', subtitle: 'Student-facing updates'),
          const SizedBox(height: 12),
          ...notices.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 10),
              child: _NoticeCard(copy: item),
            ),
          ),
        ],
      ],
    );
  }
}
`);

  sections.push(`
class AcademicsScreen extends StatelessWidget {
  const AcademicsScreen({
    super.key,
    required this.business,
    required this.app,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;

  @override
  Widget build(BuildContext context) {
    final programs = _stringList(app['programs']);
    final facilities = _stringList(app['facilities']);

    return ListView(
      padding: const EdgeInsets.fromLTRB(18, 8, 18, 120),
      children: [
        _SectionBanner(
          title: 'Academics & Facilities',
          subtitle: _text(business['type'], 'Institute') + ' · ' + _text(business['locationLabel']),
        ),
        const SizedBox(height: 18),
        const _SectionTitle(title: 'Programs', subtitle: 'Learning pathways'),
        const SizedBox(height: 12),
        if (programs.isNotEmpty)
          ...programs.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _DetailCard(
                title: item,
                body: 'Configured from Generator Studio and editable at any time before rebuilding the app.',
              ),
            ),
          )
        else
          const _EmptyCard(copy: 'Add programs in Generator Studio to build a stronger academics screen.'),
        const SizedBox(height: 22),
        const _SectionTitle(title: 'Facilities', subtitle: 'Campus support'),
        const SizedBox(height: 12),
        if (facilities.isNotEmpty)
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: facilities.map((item) => _TagChip(label: item)).toList(),
          )
        else
          const _EmptyCard(copy: 'Add facilities in Generator Studio to highlight labs, transport, libraries, and support services.'),
        if (_text(app['admissions_note']).isNotEmpty) ...[
          const SizedBox(height: 22),
          const _SectionTitle(title: 'Admissions', subtitle: 'Enrollment guidance'),
          const SizedBox(height: 12),
          _GlassCard(
            child: Text(
              _text(app['admissions_note']),
              style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.65),
            ),
          ),
        ],
      ],
    );
  }
}

class PeopleScreen extends StatelessWidget {
  const PeopleScreen({
    super.key,
    required this.business,
    required this.app,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;

  @override
  Widget build(BuildContext context) {
    final staff = _blockList(app['staff']);
    final notices = _stringList(app['notices']);

    return ListView(
      padding: const EdgeInsets.fromLTRB(18, 8, 18, 120),
      children: [
        _SectionBanner(
          title: 'Leadership & People',
          subtitle: _text(business['name']),
        ),
        if (_text(app['director_message']).isNotEmpty) ...[
          const SizedBox(height: 18),
          _DetailCard(
            title: _text(app['director_name'], 'Institute lead'),
            subtitle: _text(app['director_role']),
            body: _text(app['director_message']),
          ),
        ],
        const SizedBox(height: 22),
        const _SectionTitle(title: 'Staff', subtitle: 'Faculty and team'),
        const SizedBox(height: 12),
        if (staff.isNotEmpty)
          ...staff.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _StaffCard(
                name: _text(item['name'], 'Staff Member'),
                role: _text(item['role']),
                bio: _text(item['bio']),
                imageUrl: _text(item['image']),
              ),
            ),
          )
        else
          const _EmptyCard(copy: 'Add staff profiles in Generator Studio to build a proper people screen.'),
        if (notices.isNotEmpty) ...[
          const SizedBox(height: 22),
          const _SectionTitle(title: 'Announcements', subtitle: 'Community updates'),
          const SizedBox(height: 12),
          ...notices.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 10),
              child: _NoticeCard(copy: item),
            ),
          ),
        ],
      ],
    );
  }
}

class MediaScreen extends StatefulWidget {
  const MediaScreen({
    super.key,
    required this.business,
    required this.app,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;

  @override
  State<MediaScreen> createState() => _MediaScreenState();
}

class _MediaScreenState extends State<MediaScreen> {
  late String _selectedView;

  @override
  void initState() {
    super.initState();
    _selectedView = _availableViews.first;
  }

  @override
  void didUpdateWidget(covariant MediaScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    final availableViews = _availableViews;
    if (!availableViews.contains(_selectedView)) {
      _selectedView = availableViews.first;
    }
  }

  List<String> get _availableViews {
    final social = _mapValue(widget.app['social']);
    final videos = _blockList(widget.app['videos']);
    final views = <String>[];
    if (videos.isNotEmpty || _resolveFeaturedVideo(videos, _text(social['youtube'])) != null) {
      views.add('videos');
    }
    if (_stringList(widget.app['gallery']).isNotEmpty) {
      views.add('gallery');
    }
    if (_text(social['facebook']).isNotEmpty) {
      views.add('facebook');
    }
    if (_text(social['youtube']).isNotEmpty) {
      views.add('youtube');
    }
    return views.isNotEmpty ? views : <String>['videos'];
  }

  @override
  Widget build(BuildContext context) {
    final app = widget.app;
    final social = _mapValue(app['social']);
    final contact = _mapValue(app['contact']);
    final gallery = _stringList(app['gallery']);
    final videos = _blockList(app['videos']);
    final playlists = _blockList(app['playlists']);
    final youtube = _text(social['youtube']);
    final facebook = _text(social['facebook']);
    final fallbackImage = _firstNonEmpty(<String>[
      _text(app['hero_image_url']),
      ...gallery,
    ]);
    final featuredVideo = _resolveFeaturedVideo(videos, youtube);

    return Padding(
      padding: const EdgeInsets.fromLTRB(18, 8, 18, 120),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SectionBanner(
            title: 'Media Studio',
            subtitle: 'Switch between videos, gallery, and live social feeds',
          ),
          const SizedBox(height: 18),
          _ChannelProfileCard(
            title: _text(app['app_name'], _text(widget.business['name'], 'Institute')),
            subtitle: _text(app['app_tagline'], 'Official media profile'),
            channelUrl: _youtubeExternalUrl(youtube),
            websiteUrl: _text(contact['website']),
            logoUrl: _text(app['logo_url']),
          ),
          const SizedBox(height: 18),
          _SourcePickerCard(
            title: 'Media sources',
            subtitle: 'Choose what should fill the main viewing area.',
            options: _availableViews,
            selected: _selectedView,
            onSelected: (next) {
              setState(() {
                _selectedView = next;
              });
            },
          ),
          const SizedBox(height: 18),
          Expanded(
            child: _buildViewport(
              context,
              gallery: gallery,
              videos: videos,
              playlists: playlists,
              featuredVideo: featuredVideo,
              fallbackImage: fallbackImage,
              facebook: facebook,
              youtube: youtube,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildViewport(
    BuildContext context, {
    required List<String> gallery,
    required List<Map<String, dynamic>> videos,
    required List<Map<String, dynamic>> playlists,
    required Map<String, dynamic>? featuredVideo,
    required String fallbackImage,
    required String facebook,
    required String youtube,
  }) {
    switch (_selectedView) {
      case 'gallery':
        return _GalleryViewport(gallery: gallery);
      case 'facebook':
        return _LiveWebPanel(
          title: 'Facebook page',
          subtitle: 'Scroll the public page directly inside the app.',
          viewUrl: _facebookPluginUrl(facebook),
          sourceUrl: facebook,
          openLabel: 'Open Facebook',
        );
      case 'youtube':
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (featuredVideo != null) ...[
              _FeaturedVideoCard(
                label: 'Latest YouTube update',
                title: _text(featuredVideo['title'], 'Latest upload'),
                url: _text(featuredVideo['url']),
                fallbackImage: fallbackImage,
              ),
              const SizedBox(height: 12),
            ],
            Expanded(
              child: _LiveWebPanel(
                title: _youtubePanelTitle(youtube),
                subtitle: 'Browse and scroll the linked YouTube page without leaving the app.',
                viewUrl: _youtubeBrowserUrl(youtube),
                sourceUrl: _youtubeExternalUrl(youtube),
                openLabel: _youtubeVideoIdFromUrl(youtube).isNotEmpty ? 'Open on YouTube' : 'Open channel',
              ),
            ),
          ],
        );
      case 'videos':
      default:
        return _VideoLibraryViewport(
          playlists: playlists,
          videos: videos,
          featuredVideo: featuredVideo,
          fallbackImage: fallbackImage,
        );
    }
  }
}

class UpdatesScreen extends StatefulWidget {
  const UpdatesScreen({
    super.key,
    required this.business,
    required this.app,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;

  @override
  State<UpdatesScreen> createState() => _UpdatesScreenState();
}

class _UpdatesScreenState extends State<UpdatesScreen> {
  late String _selectedSource;

  @override
  void initState() {
    super.initState();
    _selectedSource = _availableSources.first;
  }

  @override
  void didUpdateWidget(covariant UpdatesScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    final availableSources = _availableSources;
    if (!availableSources.contains(_selectedSource)) {
      _selectedSource = availableSources.first;
    }
  }

  List<String> get _availableSources {
    final social = _mapValue(widget.app['social']);
    final sources = <String>[];
    if (_text(social['youtube']).isNotEmpty) {
      sources.add('youtube');
    }
    if (_text(social['facebook']).isNotEmpty) {
      sources.add('facebook');
    }
    return sources.isNotEmpty ? sources : <String>['youtube'];
  }

  @override
  Widget build(BuildContext context) {
    final app = widget.app;
    final contact = _mapValue(app['contact']);
    final social = _mapValue(app['social']);
    final videos = _blockList(app['videos']);
    final gallery = _stringList(app['gallery']);
    final facebook = _text(social['facebook']);
    final youtube = _text(social['youtube']);
    final fallbackImage = _firstNonEmpty(<String>[
      _text(app['hero_image_url']),
      ...gallery,
    ]);
    final featuredVideo = _resolveFeaturedVideo(videos, youtube);

    return Padding(
      padding: const EdgeInsets.fromLTRB(18, 8, 18, 120),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SectionBanner(
            title: 'Updates & Contact',
            subtitle: 'Two live update channels with a larger viewing area',
          ),
          const SizedBox(height: 18),
          _ContactActionCard(
            title: _text(app['contact_headline'], 'Reach the institute'),
            address: _text(contact['address']),
            phone: _text(contact['phone']),
            email: _text(contact['email']),
            website: _text(contact['website']),
          ),
          const SizedBox(height: 18),
          _SourcePickerCard(
            title: 'Update source',
            subtitle: 'Switch the live card between Facebook and YouTube.',
            options: _availableSources,
            selected: _selectedSource,
            onSelected: (next) {
              setState(() {
                _selectedSource = next;
              });
            },
          ),
          const SizedBox(height: 18),
          Expanded(
            child: _buildViewport(
              featuredVideo: featuredVideo,
              fallbackImage: fallbackImage,
              facebook: facebook,
              youtube: youtube,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildViewport({
    required Map<String, dynamic>? featuredVideo,
    required String fallbackImage,
    required String facebook,
    required String youtube,
  }) {
    if (facebook.isEmpty && youtube.isEmpty) {
      return const Center(
        child: _EmptyCard(copy: 'Add Facebook or YouTube links in Generator Studio to render live updates here.'),
      );
    }

    if (_selectedSource == 'facebook' && facebook.isNotEmpty) {
      return _LiveWebPanel(
        title: 'Facebook updates',
        subtitle: 'Scroll the timeline directly inside the update screen.',
        viewUrl: _facebookPluginUrl(facebook),
        sourceUrl: facebook,
        openLabel: 'Open Facebook',
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (featuredVideo != null) ...[
          _FeaturedVideoCard(
            label: 'Latest video update',
            title: _text(featuredVideo['title'], 'Latest upload'),
            url: _text(featuredVideo['url']),
            fallbackImage: fallbackImage,
          ),
          const SizedBox(height: 12),
        ],
        Expanded(
          child: _LiveWebPanel(
            title: _youtubePanelTitle(youtube),
            subtitle: 'Scroll the latest linked YouTube page inside the app.',
            viewUrl: _youtubeBrowserUrl(youtube),
            sourceUrl: _youtubeExternalUrl(youtube),
            openLabel: _youtubeVideoIdFromUrl(youtube).isNotEmpty ? 'Open on YouTube' : 'Open channel',
          ),
        ),
      ],
    );
  }
}
`);

  sections.push(`
class _HomeHero extends StatelessWidget {
  const _HomeHero({
    required this.business,
    required this.app,
    required this.onNavigate,
  });

  final Map<String, dynamic> business;
  final Map<String, dynamic> app;
  final ValueChanged<int> onNavigate;

  @override
  Widget build(BuildContext context) {
    final title = _text(app['intro_title'], _text(business['name'], 'Institute'));
    final subtitle = _text(app['app_tagline'], _text(business['type']));
    final summary = _text(app['intro_body']);
    final imageUrl = _text(app['hero_image_url']);

    return _GlassCard(
      padding: EdgeInsets.zero,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(28),
        child: SizedBox(
          height: 320,
          child: Stack(
            fit: StackFit.expand,
            children: [
              DecoratedBox(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      Theme.of(context).colorScheme.primary.withOpacity(0.92),
                      Theme.of(context).colorScheme.secondary.withOpacity(0.62),
                      const Color(0xFF0F172A),
                    ],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                ),
              ),
              if (imageUrl.isNotEmpty)
                Opacity(
                  opacity: 0.24,
                  child: Image.network(
                    imageUrl,
                    fit: BoxFit.cover,
                    errorBuilder: (_, __, ___) => const SizedBox.shrink(),
                  ),
                ),
              Padding(
                padding: const EdgeInsets.all(22),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        _LogoAvatar(name: _text(app['app_name'], title), logoUrl: _text(app['logo_url']), radius: 30),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                _text(app['app_name'], title),
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis,
                                style: Theme.of(context).textTheme.titleLarge?.copyWith(
                                      color: Colors.white,
                                      fontWeight: FontWeight.w800,
                                    ),
                              ),
                              if (subtitle.isNotEmpty)
                                Text(
                                  subtitle,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                                        color: Colors.white.withOpacity(0.84),
                                      ),
                                ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const Spacer(),
                    Text(
                      title,
                      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                            color: Colors.white,
                            fontWeight: FontWeight.w800,
                          ),
                    ),
                    const SizedBox(height: 10),
                    Text(
                      summary,
                      maxLines: 4,
                      overflow: TextOverflow.ellipsis,
                      style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                            color: Colors.white.withOpacity(0.88),
                            height: 1.55,
                          ),
                    ),
                    const SizedBox(height: 16),
                    Wrap(
                      spacing: 10,
                      runSpacing: 10,
                      children: [
                        _ActionChip(
                          label: 'Open Media',
                          icon: Icons.play_circle_fill_rounded,
                          onTap: () => onNavigate(3),
                          isPrimary: true,
                        ),
                        _ActionChip(
                          label: 'See Updates',
                          icon: Icons.campaign_rounded,
                          onTap: () => onNavigate(4),
                          isPrimary: false,
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _SectionBanner extends StatelessWidget {
  const _SectionBanner({required this.title, required this.subtitle});

  final String title;
  final String subtitle;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            subtitle,
            style: Theme.of(context).textTheme.labelLarge?.copyWith(
                  color: Theme.of(context).colorScheme.primary,
                ),
          ),
          const SizedBox(height: 6),
          Text(
            title,
            style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800),
          ),
        ],
      ),
    );
  }
}

class _SectionTitle extends StatelessWidget {
  const _SectionTitle({required this.title, required this.subtitle});

  final String title;
  final String subtitle;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          subtitle,
          style: Theme.of(context).textTheme.labelLarge?.copyWith(
                color: Theme.of(context).colorScheme.primary,
              ),
        ),
        const SizedBox(height: 4),
        Text(
          title,
          style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800),
        ),
      ],
    );
  }
}

class _GlassCard extends StatelessWidget {
  const _GlassCard({
    required this.child,
    this.padding = const EdgeInsets.all(20),
  });

  final Widget child;
  final EdgeInsetsGeometry padding;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: padding,
      decoration: _softCardDecoration(context),
      child: child,
    );
  }
}

class _MetricTile extends StatelessWidget {
  const _MetricTile({required this.value, required this.label});

  final String value;
  final String label;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 156,
      padding: const EdgeInsets.all(18),
      decoration: _softCardDecoration(context),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            value,
            style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 8),
          Text(
            label,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
          ),
        ],
      ),
    );
  }
}

class _DetailCard extends StatelessWidget {
  const _DetailCard({
    required this.title,
    required this.body,
    this.subtitle = '',
  });

  final String title;
  final String subtitle;
  final String body;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (subtitle.isNotEmpty)
            Text(
              subtitle,
              style: Theme.of(context).textTheme.labelLarge?.copyWith(
                    color: Theme.of(context).colorScheme.primary,
                  ),
            ),
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          if (body.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(
              body,
              style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.62),
            ),
          ],
        ],
      ),
    );
  }
}

class _NoticeCard extends StatelessWidget {
  const _NoticeCard({required this.copy});

  final String copy;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
        borderRadius: BorderRadius.circular(22),
        border: Border.all(color: Theme.of(context).colorScheme.primary.withOpacity(0.18)),
      ),
      child: Text(
        copy,
        style: Theme.of(context).textTheme.bodyMedium?.copyWith(height: 1.55),
      ),
    );
  }
}

class _StaffCard extends StatelessWidget {
  const _StaffCard({
    required this.name,
    required this.role,
    required this.bio,
    required this.imageUrl,
  });

  final String name;
  final String role;
  final String bio;
  final String imageUrl;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _LogoAvatar(name: name, logoUrl: imageUrl, radius: 34),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  name,
                  style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800),
                ),
                if (role.isNotEmpty)
                  Text(
                    role,
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
                  ),
                if (bio.isNotEmpty) ...[
                  const SizedBox(height: 8),
                  Text(
                    bio,
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(height: 1.55),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`);

  sections.push(`
class _GalleryTile extends StatelessWidget {
  const _GalleryTile({required this.url, required this.fallbackLabel});

  final String url;
  final String fallbackLabel;

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(24),
      child: SizedBox(
        width: 250,
        child: DecoratedBox(
          decoration: _softCardDecoration(context),
          child: Image.network(
            url,
            fit: BoxFit.cover,
            errorBuilder: (_, __, ___) => _ImageFallback(label: fallbackLabel),
          ),
        ),
      ),
    );
  }
}

class _ChannelProfileCard extends StatelessWidget {
  const _ChannelProfileCard({
    required this.title,
    required this.subtitle,
    required this.channelUrl,
    required this.websiteUrl,
    required this.logoUrl,
  });

  final String title;
  final String subtitle;
  final String channelUrl;
  final String websiteUrl;
  final String logoUrl;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _LogoAvatar(name: title, logoUrl: logoUrl, radius: 34),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
                ),
                const SizedBox(height: 4),
                Text(
                  subtitle,
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
                ),
                const SizedBox(height: 12),
                Wrap(
                  spacing: 10,
                  runSpacing: 10,
                  children: [
                    if (channelUrl.isNotEmpty)
                      _ActionChip(
                        label: channelUrl.contains('watch?v=') ? 'Open YouTube' : 'Open channel',
                        icon: Icons.ondemand_video_rounded,
                        onTap: () => _openExternal(channelUrl),
                        isPrimary: true,
                      ),
                    if (websiteUrl.isNotEmpty)
                      _ActionChip(
                        label: 'Open website',
                        icon: Icons.language_rounded,
                        onTap: () => _openExternal(websiteUrl),
                      ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _PlaylistCard extends StatelessWidget {
  const _PlaylistCard({
    required this.title,
    required this.url,
    required this.description,
  });

  final String title;
  final String url;
  final String description;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          if (description.isNotEmpty) ...[
            const SizedBox(height: 8),
            Text(
              description,
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(height: 1.55),
            ),
          ],
          if (url.isNotEmpty) ...[
            const SizedBox(height: 14),
            FilledButton.tonalIcon(
              onPressed: () => _openExternal(url),
              icon: const Icon(Icons.queue_play_next_rounded),
              label: const Text('Open playlist'),
            ),
          ],
        ],
      ),
    );
  }
}

class _VideoCard extends StatelessWidget {
  const _VideoCard({
    required this.title,
    required this.url,
    required this.fallbackImage,
  });

  final String title;
  final String url;
  final String fallbackImage;

  @override
  Widget build(BuildContext context) {
    final previewImage = _videoPreviewImage(url, fallbackImage);
    return _GlassCard(
      padding: EdgeInsets.zero,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(28)),
            child: SizedBox(
              height: 190,
              width: double.infinity,
              child: previewImage.isNotEmpty
                  ? Image.network(
                      previewImage,
                      fit: BoxFit.cover,
                      errorBuilder: (_, __, ___) => _ImageFallback(label: 'Video'),
                    )
                  : const _ImageFallback(label: 'Video'),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(18),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
                ),
                const SizedBox(height: 6),
                Text(
                  _videoTypeLabel(url),
                  style: Theme.of(context).textTheme.labelLarge?.copyWith(
                        color: Theme.of(context).colorScheme.primary,
                      ),
                ),
                const SizedBox(height: 10),
                Text(
                  url,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
                ),
                const SizedBox(height: 14),
                FilledButton.tonalIcon(
                  onPressed: () {
                    Navigator.of(context).push(
                      MaterialPageRoute<void>(
                        builder: (_) => VideoPlayerPage(title: title, url: url),
                      ),
                    );
                  },
                  icon: const Icon(Icons.play_arrow_rounded),
                  label: const Text('Play video'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _VideoLibraryViewport extends StatelessWidget {
  const _VideoLibraryViewport({
    required this.playlists,
    required this.videos,
    required this.featuredVideo,
    required this.fallbackImage,
  });

  final List<Map<String, dynamic>> playlists;
  final List<Map<String, dynamic>> videos;
  final Map<String, dynamic>? featuredVideo;
  final String fallbackImage;

  @override
  Widget build(BuildContext context) {
    final libraryVideos = <Map<String, dynamic>>[...videos];
    if (libraryVideos.isEmpty && featuredVideo != null) {
      libraryVideos.add(featuredVideo!);
    }

    return ListView(
      padding: EdgeInsets.zero,
      children: [
        if (playlists.isNotEmpty) ...[
          const _SectionTitle(title: 'Playlists', subtitle: 'Organized viewing lanes'),
          const SizedBox(height: 12),
          ...playlists.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _PlaylistCard(
                title: _text(item['title'], 'Featured playlist'),
                url: _text(item['url']),
                description: _text(item['description']),
              ),
            ),
          ),
          const SizedBox(height: 10),
        ],
        const _SectionTitle(title: 'Playable videos', subtitle: 'Tap any card to play inside the app'),
        const SizedBox(height: 12),
        if (libraryVideos.isNotEmpty)
          ...libraryVideos.map(
            (item) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _VideoCard(
                title: _text(item['title'], 'Institute video'),
                url: _text(item['url']),
                fallbackImage: fallbackImage,
              ),
            ),
          )
        else
          const _EmptyCard(copy: 'Add YouTube, Vimeo, or direct video links in Generator Studio to create playable cards.'),
      ],
    );
  }
}

class _GalleryViewport extends StatelessWidget {
  const _GalleryViewport({required this.gallery});

  final List<String> gallery;

  @override
  Widget build(BuildContext context) {
    if (gallery.isEmpty) {
      return const Center(
        child: _EmptyCard(copy: 'Add gallery image links in Generator Studio to build this section.'),
      );
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        final crossAxisCount = constraints.maxWidth < 640 ? 1 : 2;
        final aspectRatio = crossAxisCount == 1 ? 1.55 : 1.14;
        return GridView.builder(
          padding: EdgeInsets.zero,
          itemCount: gallery.length,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: crossAxisCount,
            mainAxisSpacing: 12,
            crossAxisSpacing: 12,
            childAspectRatio: aspectRatio,
          ),
          itemBuilder: (context, index) {
            final item = gallery[index];
            return ClipRRect(
              borderRadius: BorderRadius.circular(24),
              child: DecoratedBox(
                decoration: _softCardDecoration(context),
                child: Image.network(
                  item,
                  fit: BoxFit.cover,
                  errorBuilder: (_, __, ___) => _ImageFallback(label: 'Image ' + (index + 1).toString()),
                ),
              ),
            );
          },
        );
      },
    );
  }
}

class _SourcePickerCard extends StatelessWidget {
  const _SourcePickerCard({
    required this.title,
    required this.subtitle,
    required this.options,
    required this.selected,
    required this.onSelected,
  });

  final String title;
  final String subtitle;
  final List<String> options;
  final String selected;
  final ValueChanged<String> onSelected;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 6),
          Text(
            subtitle,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
          ),
          const SizedBox(height: 14),
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SegmentedButton<String>(
              segments: options
                  .map(
                    (item) => ButtonSegment<String>(
                      value: item,
                      icon: Icon(_sourceIcon(item)),
                      label: Text(_sourceLabel(item)),
                    ),
                  )
                  .toList(),
              selected: <String>{selected},
              showSelectedIcon: false,
              onSelectionChanged: (selection) {
                if (selection.isEmpty) {
                  return;
                }
                onSelected(selection.first);
              },
            ),
          ),
        ],
      ),
    );
  }
}

class _FeaturedVideoCard extends StatelessWidget {
  const _FeaturedVideoCard({
    required this.label,
    required this.title,
    required this.url,
    required this.fallbackImage,
  });

  final String label;
  final String title;
  final String url;
  final String fallbackImage;

  @override
  Widget build(BuildContext context) {
    final previewImage = _videoPreviewImage(url, fallbackImage);
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(22),
            child: SizedBox(
              height: 180,
              width: double.infinity,
              child: previewImage.isNotEmpty
                  ? Image.network(
                      previewImage,
                      fit: BoxFit.cover,
                      errorBuilder: (_, __, ___) => const _ImageFallback(label: 'Video'),
                    )
                  : const _ImageFallback(label: 'Video'),
            ),
          ),
          const SizedBox(height: 14),
          Text(
            label,
            style: Theme.of(context).textTheme.labelLarge?.copyWith(
                  color: Theme.of(context).colorScheme.primary,
                ),
          ),
          const SizedBox(height: 4),
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 6),
          Text(
            _videoTypeLabel(url),
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
          ),
          const SizedBox(height: 14),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              FilledButton.tonalIcon(
                onPressed: () {
                  Navigator.of(context).push(
                    MaterialPageRoute<void>(
                      builder: (_) => VideoPlayerPage(title: title, url: url),
                    ),
                  );
                },
                icon: const Icon(Icons.play_arrow_rounded),
                label: const Text('Play now'),
              ),
              OutlinedButton.icon(
                onPressed: () => _openExternal(url),
                icon: const Icon(Icons.open_in_new_rounded),
                label: const Text('Open source'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _ContactActionCard extends StatelessWidget {
  const _ContactActionCard({
    required this.title,
    required this.address,
    required this.phone,
    required this.email,
    required this.website,
  });

  final String title;
  final String address;
  final String phone;
  final String email;
  final String website;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800),
          ),
          if (address.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(address, style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.55)),
          ],
          const SizedBox(height: 16),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              if (phone.isNotEmpty) _ActionChip(label: 'Call', icon: Icons.call_rounded, onTap: () => _openExternal('tel:' + phone)),
              if (email.isNotEmpty) _ActionChip(label: 'Email', icon: Icons.mail_outline_rounded, onTap: () => _openExternal('mailto:' + email)),
              if (website.isNotEmpty) _ActionChip(label: 'Website', icon: Icons.language_rounded, onTap: () => _openExternal(website), isPrimary: true),
            ],
          ),
        ],
      ),
    );
  }
}

class _ActionChip extends StatelessWidget {
  const _ActionChip({
    required this.label,
    required this.icon,
    required this.onTap,
    this.isPrimary = false,
  });

  final String label;
  final IconData icon;
  final VoidCallback onTap;
  final bool isPrimary;

  @override
  Widget build(BuildContext context) {
    if (isPrimary) {
      return FilledButton.tonalIcon(
        onPressed: onTap,
        icon: Icon(icon),
        label: Text(label),
      );
    }
    return OutlinedButton.icon(
      onPressed: onTap,
      icon: Icon(icon),
      label: Text(label),
    );
  }
}

class _TagChip extends StatelessWidget {
  const _TagChip({required this.label});

  final String label;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.92),
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.7)),
      ),
      child: Text(label),
    );
  }
}

class _EmptyCard extends StatelessWidget {
  const _EmptyCard({required this.copy});

  final String copy;

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      child: Text(
        copy,
        style: Theme.of(context).textTheme.bodyLarge?.copyWith(height: 1.55),
      ),
    );
  }
}

class _LogoAvatar extends StatelessWidget {
  const _LogoAvatar({
    required this.name,
    required this.logoUrl,
    required this.radius,
  });

  final String name;
  final String logoUrl;
  final double radius;

  @override
  Widget build(BuildContext context) {
    final size = radius * 2;
    final fallback = _ImageFallback(label: _initials(name));
    return ClipRRect(
      borderRadius: BorderRadius.circular(radius * 0.78),
      child: SizedBox(
        width: size,
        height: size,
        child: logoUrl.isNotEmpty
            ? Image.network(
                logoUrl,
                fit: BoxFit.cover,
                errorBuilder: (_, __, ___) => fallback,
              )
            : fallback,
      ),
    );
  }
}

class _ImageFallback extends StatelessWidget {
  const _ImageFallback({required this.label});

  final String label;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            Theme.of(context).colorScheme.primary.withOpacity(0.18),
            Theme.of(context).colorScheme.secondary.withOpacity(0.1),
          ],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
      ),
      child: Center(
        child: Text(
          label,
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                color: Theme.of(context).colorScheme.primary,
                fontWeight: FontWeight.w800,
              ),
        ),
      ),
    );
  }
}

class _LiveWebPanel extends StatefulWidget {
  const _LiveWebPanel({
    required this.title,
    required this.subtitle,
    required this.viewUrl,
    required this.sourceUrl,
    required this.openLabel,
  });

  final String title;
  final String subtitle;
  final String viewUrl;
  final String sourceUrl;
  final String openLabel;

  @override
  State<_LiveWebPanel> createState() => _LiveWebPanelState();
}

class _LiveWebPanelState extends State<_LiveWebPanel> {
  late final WebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..loadRequest(Uri.parse(widget.viewUrl));
  }

  @override
  void didUpdateWidget(covariant _LiveWebPanel oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.viewUrl != widget.viewUrl) {
      _controller.loadRequest(Uri.parse(widget.viewUrl));
    }
  }

  @override
  Widget build(BuildContext context) {
    return _GlassCard(
      padding: const EdgeInsets.all(14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            widget.title,
            style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 4),
          Text(
            widget.subtitle,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.black54),
          ),
          const SizedBox(height: 12),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              OutlinedButton.icon(
                onPressed: () => _controller.reload(),
                icon: const Icon(Icons.refresh_rounded),
                label: const Text('Refresh'),
              ),
              FilledButton.tonalIcon(
                onPressed: () => _openExternal(widget.sourceUrl),
                icon: const Icon(Icons.open_in_new_rounded),
                label: Text(widget.openLabel),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Expanded(
            // Keep live feeds in an expanded viewport so scroll gestures stay inside the feed.
            child: ClipRRect(
              borderRadius: BorderRadius.circular(20),
              child: WebViewWidget(controller: _controller),
            ),
          ),
        ],
      ),
    );
  }
}

class VideoPlayerPage extends StatefulWidget {
  const VideoPlayerPage({
    super.key,
    required this.title,
    required this.url,
  });

  final String title;
  final String url;

  @override
  State<VideoPlayerPage> createState() => _VideoPlayerPageState();
}

class _VideoPlayerPageState extends State<VideoPlayerPage> {
  VideoPlayerController? _controller;
  Future<void>? _initializeFuture;
  WebViewController? _webController;
  YoutubePlayerController? _youtubeController;
  late final String _embedUrl;
  late final String _youtubeVideoId;

  @override
  void initState() {
    super.initState();
    _youtubeVideoId = _youtubeVideoIdFromUrl(widget.url);
    _embedUrl = _embedUrlForVideo(widget.url);
    // Prefer the dedicated YouTube player when a video id is available.
    if (_youtubeVideoId.isNotEmpty) {
      _youtubeController = YoutubePlayerController.fromVideoId(
        videoId: _youtubeVideoId,
        autoPlay: false,
        params: const YoutubePlayerParams(
          showControls: true,
          showFullscreenButton: true,
          enableJavaScript: true,
          strictRelatedVideos: true,
        ),
      );
      return;
    }
    if (_isDirectVideoUrl(widget.url)) {
      final controller = VideoPlayerController.networkUrl(Uri.parse(widget.url));
      _controller = controller;
      _initializeFuture = controller.initialize();
    } else {
      final webController = WebViewController()
        ..setJavaScriptMode(JavaScriptMode.unrestricted);
      if (_embedUrl.isNotEmpty) {
        webController.loadHtmlString(_videoEmbedDocument(_embedUrl, widget.title));
      } else {
        webController.loadRequest(Uri.parse(widget.url));
      }
      _webController = webController;
    }
  }

  @override
  void dispose() {
    _youtubeController?.close();
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Padding(
        padding: const EdgeInsets.all(18),
        child: _youtubeController != null
            ? ListView(
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(24),
                    child: YoutubePlayer(
                      controller: _youtubeController!,
                      aspectRatio: 16 / 9,
                    ),
                  ),
                  const SizedBox(height: 18),
                  Wrap(
                    spacing: 10,
                    runSpacing: 10,
                    children: [
                      FilledButton.tonalIcon(
                        onPressed: () => _youtubeController!.loadVideoById(videoId: _youtubeVideoId),
                        icon: const Icon(Icons.refresh_rounded),
                        label: const Text('Restart video'),
                      ),
                      OutlinedButton.icon(
                        onPressed: () => _openExternal(_youtubeExternalUrl(widget.url)),
                        icon: const Icon(Icons.open_in_new_rounded),
                        label: const Text('Open source'),
                      ),
                    ],
                  ),
                ],
              )
            : _controller != null
            ? FutureBuilder<void>(
                future: _initializeFuture,
                builder: (context, snapshot) {
                  if (snapshot.connectionState != ConnectionState.done) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final controller = _controller!;
                  return Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.circular(24),
                        child: AspectRatio(
                          aspectRatio: controller.value.aspectRatio == 0 ? 16 / 9 : controller.value.aspectRatio,
                          child: VideoPlayer(controller),
                        ),
                      ),
                      const SizedBox(height: 18),
                      Wrap(
                        spacing: 10,
                        children: [
                          FilledButton.tonalIcon(
                            onPressed: () {
                              if (controller.value.isPlaying) {
                                controller.pause();
                              } else {
                                controller.play();
                              }
                              setState(() {});
                            },
                            icon: Icon(controller.value.isPlaying ? Icons.pause_rounded : Icons.play_arrow_rounded),
                            label: Text(controller.value.isPlaying ? 'Pause' : 'Play'),
                          ),
                          OutlinedButton.icon(
                            onPressed: () => _openExternal(widget.url),
                            icon: const Icon(Icons.open_in_new_rounded),
                            label: const Text('Open source'),
                          ),
                        ],
                      ),
                    ],
                  );
                },
              )
            : ClipRRect(
                borderRadius: BorderRadius.circular(24),
                child: WebViewWidget(controller: _webController!),
              ),
      ),
    );
  }
}
`);

  sections.push(`
BoxDecoration _softCardDecoration(BuildContext context) {
  return BoxDecoration(
    color: Colors.white.withOpacity(0.84),
    borderRadius: BorderRadius.circular(28),
    border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.34)),
    boxShadow: [
      BoxShadow(
        color: Colors.black.withOpacity(0.06),
        blurRadius: 24,
        offset: const Offset(0, 10),
      ),
    ],
  );
}

Map<String, dynamic> _mapValue(dynamic input) {
  if (input is Map<String, dynamic>) return input;
  if (input is Map) return input.map((key, value) => MapEntry(key.toString(), value));
  return <String, dynamic>{};
}

List<Map<String, dynamic>> _blockList(dynamic input) {
  if (input is! List) return <Map<String, dynamic>>[];
  return input.map<Map<String, dynamic>>((item) => _mapValue(item)).where((item) => item.isNotEmpty).toList();
}

List<String> _stringList(dynamic input) {
  if (input is! List) return <String>[];
  return input.map((item) => item?.toString().trim() ?? '').where((item) => item.isNotEmpty).toList();
}

String _text(dynamic value, [String fallback = '']) {
  final text = value?.toString().trim() ?? '';
  return text.isNotEmpty ? text : fallback;
}

String _firstNonEmpty(List<String> values) {
  for (final value in values) {
    if (value.trim().isNotEmpty) {
      return value.trim();
    }
  }
  return '';
}

Color _parseColor(String value) {
  final cleaned = value.replaceAll('#', '').trim();
  final hex = cleaned.length == 6 ? 'FF' + cleaned : cleaned;
  return Color(int.tryParse(hex, radix: 16) ?? 0xFF355DA8);
}

bool _isDirectVideoUrl(String url) {
  return RegExp(r'\\.(mp4|webm|ogg)(\\?.*)?$', caseSensitive: false).hasMatch(url);
}

Map<String, dynamic>? _resolveFeaturedVideo(List<Map<String, dynamic>> videos, String youtubeUrl) {
  if (videos.isNotEmpty) {
    return videos.first;
  }
  final videoUrl = _canonicalYoutubeWatchUrl(youtubeUrl);
  if (videoUrl.isEmpty) {
    return null;
  }
  return <String, dynamic>{
    'title': 'Latest YouTube upload',
    'url': videoUrl,
  };
}

String _sourceLabel(String value) {
  switch (value) {
    case 'videos':
      return 'Videos';
    case 'gallery':
      return 'Gallery';
    case 'facebook':
      return 'Facebook';
    case 'youtube':
      return 'YouTube';
    default:
      return 'View';
  }
}

IconData _sourceIcon(String value) {
  switch (value) {
    case 'videos':
      return Icons.play_circle_fill_rounded;
    case 'gallery':
      return Icons.photo_library_rounded;
    case 'facebook':
      return Icons.thumb_up_alt_rounded;
    case 'youtube':
      return Icons.ondemand_video_rounded;
    default:
      return Icons.dashboard_customize_rounded;
  }
}

String _youtubePanelTitle(String url) {
  return _youtubeVideoIdFromUrl(url).isNotEmpty ? 'YouTube watch page' : 'YouTube channel';
}

String _youtubeExternalUrl(String url) {
  final watchUrl = _canonicalYoutubeWatchUrl(url);
  return watchUrl.isNotEmpty ? watchUrl : url;
}

String _canonicalYoutubeWatchUrl(String url) {
  final id = _youtubeVideoIdFromUrl(url);
  return id.isNotEmpty ? 'https://www.youtube.com/watch?v=' + id : '';
}

String _youtubeBrowserUrl(String url) {
  final watchUrl = _canonicalYoutubeWatchUrl(url);
  if (watchUrl.isNotEmpty) {
    return watchUrl;
  }
  final uri = Uri.tryParse(url);
  if (uri == null) {
    return url;
  }
  final host = uri.host.toLowerCase();
  if (!host.contains('youtube.com')) {
    return url;
  }
  final segments = uri.pathSegments.where((segment) => segment.isNotEmpty).toList();
  if (segments.isEmpty) {
    return url;
  }
  final lastSegment = segments.last.toLowerCase();
  const pinnedSegments = <String>{
    'videos',
    'featured',
    'playlists',
    'community',
    'streams',
    'live',
    'shorts',
  };
  if (pinnedSegments.contains(lastSegment)) {
    return url;
  }
  final basePath = uri.path.endsWith('/') ? uri.path.substring(0, uri.path.length - 1) : uri.path;
  final nextPath = basePath.isEmpty ? '/videos' : basePath + '/videos';
  return uri.replace(path: nextPath).toString();
}

String _youtubeVideoIdFromUrl(String url) {
  final uri = Uri.tryParse(url);
  if (uri == null) {
    return '';
  }
  final host = uri.host.toLowerCase();
  if (host.contains('youtu.be')) {
    return uri.pathSegments.where((segment) => segment.isNotEmpty).isNotEmpty
        ? uri.pathSegments.where((segment) => segment.isNotEmpty).first
        : '';
  }
  if (!host.contains('youtube.com')) {
    return '';
  }
  final queryId = uri.queryParameters['v'] ?? '';
  if (queryId.isNotEmpty) {
    return queryId;
  }
  final segments = uri.pathSegments.where((segment) => segment.isNotEmpty).toList();
  if (segments.length > 1 && (segments.first == 'embed' || segments.first == 'shorts' || segments.first == 'live')) {
    return segments[1];
  }
  return '';
}

String _embedUrlForVideo(String url) {
  final youtubeId = _youtubeVideoIdFromUrl(url);
  if (youtubeId.isNotEmpty) {
    return 'https://www.youtube.com/embed/' + youtubeId;
  }
  final uri = Uri.tryParse(url);
  if (uri == null) return '';
  final host = uri.host.toLowerCase();
  if (host.contains('vimeo.com')) {
    final id = uri.pathSegments.where((segment) => segment.isNotEmpty).toList().isNotEmpty
        ? uri.pathSegments.where((segment) => segment.isNotEmpty).last
        : '';
    return id.isNotEmpty ? 'https://player.vimeo.com/video/' + id : '';
  }
  return '';
}

String _videoPreviewImage(String url, String fallback) {
  final youtubeId = _youtubeVideoIdFromUrl(url);
  if (youtubeId.isNotEmpty) {
    return 'https://img.youtube.com/vi/' + youtubeId + '/hqdefault.jpg';
  }
  return fallback;
}

String _videoTypeLabel(String url) {
  if (_isDirectVideoUrl(url)) return 'Direct video';
  if (_youtubeVideoIdFromUrl(url).isNotEmpty) return 'YouTube';
  if (_embedUrlForVideo(url).contains('vimeo')) return 'Vimeo';
  return 'External video';
}

String _facebookPluginUrl(String url) {
  return 'https://www.facebook.com/plugins/page.php?href=' +
      Uri.encodeComponent(url) +
      '&tabs=timeline&width=500&height=720&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true';
}

String _videoEmbedDocument(String embedUrl, String title) {
  return '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;background:#000;"><iframe src="' +
      embedUrl +
      '" title="' +
      title.replaceAll('"', '&quot;') +
      '" style="border:0;width:100vw;height:100vh;" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></body></html>';
}

Future<void> _openExternal(String url) async {
  final uri = Uri.tryParse(url);
  if (uri == null) return;
  await launchUrl(uri, mode: LaunchMode.externalApplication);
}

String _initials(String value) {
  final parts = value.trim().split(RegExp(r'\\s+')).where((part) => part.isNotEmpty).toList();
  if (parts.isEmpty) return 'I';
  final first = parts.first[0].toUpperCase();
  final second = parts.length > 1 ? parts.last[0].toUpperCase() : '';
  return first + second;
}
`);

  return sections.join("\n");
}

module.exports = {
  buildFlutterOutput,
};
